# _config.yml

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



# # Site settings
# title: Waleed's Pentesting Blog
# description: A blog about cybersecurity, penetration testing, and ethical hacking.
# author: Waleed Ahmed Butt
# email: your-email@example.com
# baseurl: "" # the subpath of your site, e.g. /blog, leave blank for root
# url: "https://your-github-username.github.io" # the base hostname & protocol for your site

# GitHub Pages theme
theme: hacker

# Other options
# paginate: 5 # Number of posts per page


# # Social media links
# social_links:
#   github: https://github.com/your-github-username
#   linkedin: https://www.linkedin.com/in/your-linkedin-username/





# # Markdown settings
# markdown: kramdown
# highlighter: rouge
